name: test
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - requests=2.25.0
  - numpy=1.19.2
  - tensorflow=2.3.0
  - pandas=1.2.1
  - tqdm=4.38.0
  - pip
  - pip:
    - mlflow==1.13.1
    - opencv-python==4.5.1.48
    - scikit-learn==0.24.1